CREATE TABLE IF NOT EXISTS addresses (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS clients (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS drivers (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    age INTEGER CHECK (age > 0) NOT NULL,
    rating NUMERIC(2) DEFAULT 5.5
);

CREATE TABLE IF NOT EXISTS cars (
    id SERIAL PRIMARY KEY,
    make VARCHAR(20) NOT NULL,
    model VARCHAR(20),
    year INTEGER DEFAULT 0 CHECK (year > 0) NOT NULL,
    mileage INTEGER DEFAULT 0 CHECK (mileage > 0),
    condition CHAR(1) NOT NULL,
    category_id INTEGER
        REFERENCES categories ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS courses (
    id SERIAL PRIMARY KEY,
    from_address_id INTEGER
        REFERENCES addresses ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
    start TIMESTAMP NOT NULL,
    bill NUMERIC(10, 2) DEFAULT 10 CHECK (bill > 0),
    car_id INTEGER
        REFERENCES cars ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
    client_id INTEGER
        REFERENCES clients ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS cars_drivers (
    car_id INTEGER
        REFERENCES cars ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
    driver_id INTEGER
        REFERENCES drivers ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
);